default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: report-_development
  username: Nikolas
  password: nikolas89

test:
  <<: *default
  database: report-_test
  username: Nikolas
  password: nikolas89

production:
  <<: *default
  database: report-_production
  username: Nikolas
  password: <%= ENV['DREPORT_DATABASE_PASSWORD'] %>
